----
<img src="../../../files/refinitiv.png" width="20%" style="vertical-align: top;">

# Data Library for Python

----

## Content layer - Search
This notebook demonstrates how to use the Search service of the Refinitiv Data Platform.

#### Learn more

To learn more about the Refinitiv Data Library for Python please join the Refinitiv Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the Refinitiv Developer Community portal you will have free access to a number of learning materials like 
 [Quick Start guides](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/quick-start), 
 [Tutorials](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/learning), 
 [Documentation](https://developers.refinitiv.com/en/api-catalog/refinitiv-data-platform/refinitiv-data-library-for-python/docs)
 and much more.

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [Refinitiv Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The Refinitiv Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the Refinitiv Data Library in the _refinitiv-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _RD_LIB_CONFIG_PATH_ environment variable. The _RD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["RD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [1]:
import refinitiv.data as rd
from refinitiv.data.content import search

## Open the data session

The open_session() function creates and open sessions based on the information contained in the refinitiv-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [2]:
rd.open_session()

## Retrieve data

### General Search

In [3]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46637038358,0x00102c80bf6b046c,459200JC6=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826899363,0x00102c53ff1f1897,US194445601=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44657843041,0x0004051bd47954e3,US114316318=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44649129642,0x00040513a4865c6c,459200HP9=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44653695161,0x00040517bba31719,459200HU8=
5,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192841929400,0x00102c2052251a71,459200JY8=
6,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46638470074,0x00102cf964da067d,US137584123=
7,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826895881,0x00102c8de61f1850,US194445610=
8,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46644611190,0x00102c00c0900d61,US161784508=
9,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",232796002153,0x00102cfffd953398,459200KS9=

### Specify number of rows to fetch

In [4]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",46637038358,0x00102c80bf6b046c,459200JC6=
1,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",192826899363,0x00102c53ff1f1897,US194445601=
2,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44657843041,0x0004051bd47954e3,US114316318=
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44649129642,0x00040513a4865c6c,459200HP9=
4,INSTRUMENTxFIXEDINCOMExGOVCORP,"International Business Machines Corp, Plain Va...",44653695161,0x00040517bba31719,459200HU8=
...,...,...,...,...,...
95,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037dfdc,<NA>
96,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037e0e3,<NA>
97,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037e1e2,<NA>
98,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037e3e0,<NA>
99,INSTRUMENTxFIXEDINCOMExGOVCORP,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037e4e7,<NA>

### Filter Expressions

In [6]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate
0,US459200JC60,459200JC6=,2015-11-09,USD,900000000,2.875,2022-11-09
1,XS1944456018,US194445601=,2019-01-31,EUR,1750000000,0.375,2023-01-31
2,XS1143163183,US114316318=,2014-11-26,EUR,1000000000,1.25,2023-05-26
3,US459200HP91,459200HP9=,2013-08-01,USD,1500000000,3.375,2023-08-01
4,US459200HU86,459200HU8=,2014-02-12,USD,2000000000,3.625,2024-02-12
5,US459200JY80,459200JY8=,2019-05-15,USD,3000000000,3.0,2024-05-15
6,XS1375841233,US137584123=,2016-03-07,EUR,750000000,1.125,2024-09-06
7,XS1944456109,US194445610=,2019-01-31,EUR,1000000000,0.875,2025-01-31
8,XS1617845083,US161784508=,2017-05-23,EUR,1000000000,0.95,2025-05-23
9,US459200KS93,459200KS9=,2022-07-27,USD,1000000000,4.0,2025-07-27

### Properties - Metadata

In [7]:
response = search.metadata.Definition(
    view = search.Views.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data() 

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,True,False,True

### Navigators

In [8]:
response = search.Definition(
    top=0,
    navigators="RCSTRBC2012Leaf"
).get_data()

### Search with Navigator option

In [9]:
response = search.Definition(
    view=search.Views.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21622940491,273610776,CSCc1
1,QUOTExCOMMODITY,"Cash Settled Cheese Futures Chain Contracts, C...",21622425217,272623267,0#CSC:
2,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21757842054,444997903,CSCM2
3,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21772665846,463861357,CSCU2
4,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21767494118,457131738,CSCQ2
5,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21778821217,471517057,CSCV2
6,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21784277336,478150068,CSCX2
7,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21790857663,485909287,CSCZ2
8,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21801133645,498573458,CSCG3
9,QUOTExCOMMODITY,CME Cash Settled Cheese Electronic Commodity F...,21819204534,520638487,CSCM3

In [10]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 17677},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 3001},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 1498},
  {'Label': 'US Department of Agriculture', 'Count': 101},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 51},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'European Energy Exchange', 'Count': 9},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [11]:
response = search.Definition(
    view=search.Views.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 11494208,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 3763389,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 49438954323649.78},
    {'Label': 'EUR',
     'Count': 1093746,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 21527212316149.0},
    {'Label': 'CNY',
     'Count': 342663,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 20044978882106.297},
    {'Label': 'JPY',
     'Count': 471204,
     'max_CouponRate': 632.0,
     'sum_FaceOutstandingUSD': 10901404501957.016},
    {'Label': 'GBP',
     'Count': 200667,
     'max_CouponRate': 120.0,
     'sum_FaceOutstandingUSD': 4186088564763.0},
    {'Label': 'CAD',
     'Count': 321134,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2573047806153.0},
    {'Label': 'INR',
     'Count': 112945,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2497247939348.0},
    {'Label': 'KRW',
     'Count': 400869,
     'max_CouponRate': 46.41,
     'sum_FaceOutstandingUSD': 2140298006081.0},
    {'Label': 'AUD',
     'Count': 149976,
     'max_CouponRate': 120.96,
     'sum_FaceOutstandingUSD': 1571159285514.6873},
    {'Label': 'BRL',
     'Count': 68846,
     'max_CouponRate': 108.5,
     'sum_FaceOutstandingUSD': 1388815848653.7607}]}}}

#### Sub-navigator

In [12]:
response = search.Definition(
    view=search.Views.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 41492,
  'LastName': {'Buckets': [{'Label': 'Wilson', 'Count': 110},
    {'Label': 'Lee', 'Count': 107}]}},
 {'Label': 'David',
  'Count': 40465,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 239},
    {'Label': 'Williams', 'Count': 164}]}},
 {'Label': 'Michael',
  'Count': 38945,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 186},
    {'Label': 'Brown', 'Count': 126}]}}]

### Search with order_by option

In [13]:
response = search.Definition(
    view=search.Views.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

   YearOfBirth                                      DocumentTitle
0         1996  Hiroyasu Saito - Gracia Inc - Chief Executive ...
1         1996  Shu Yao - Dongjiang Environmental Co Ltd - Ex-...
2         1994  Connor Campbell - Osler Diagnostics Ltd - Chie...
3         1993  Yiduitakuya Iwamoto - Polyuse Inc - Chief Exec...
4         1993  Alberto Rizzoli - V7 Ltd - Chief Executive Off...
5         1993  Tongda Wu - Paifang Technology Tianjin Co Ltd ...
6         1992  Ross Bailey - Appear Here Ltd - Chief Executiv...
7         1992  Christian Besenbruch - Deep Render Ltd - Chief...
8         1992  Ed Leon Klinger - Flock Ltd - Chief Executive ...
9         1992  Snigdha Mothukuri - Jeevan Scientific Technolo...

### Search with group_by option

In [14]:
response = search.Definition(
    view=search.Views.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,CentralBankName,DocumentTitle,RIC
0,Federal Reserve System,"United States, Policy Rates, Fed Funds Target ...",USFOMC=ECI
1,Federal Reserve System,"United States, Policy Rates, Fed Overnight Rep...",USRRP=ECI
2,European Central Bank,"Euro Zone, Policy Rates, ECB Main refinancing,...",EUECBR=ECI
3,European Central Bank,"Euro Zone, Policy Rates, ECB Deposit Rate, Reu...",EUECBD=ECI
4,Sveriges Riksbank,"Sweden, Policy Rates, Repo Rate (Effective Dat...",SERATE=ECI
5,Sveriges Riksbank,"Sweden, Riksbank Rate-Median, Reuters Polls, D...",pSERATE=M
6,Magyar Nemzeti Bank,"Hungary, Policy Rates, Base Rate, Reuters Poll...",HUINT=ECI
7,Magyar Nemzeti Bank,"Hungary, Policy Rates, Base Rate, Reuters Poll...",HUOD2=ECI
8,Central Bank of Colombia,"Colombia, Policy Rates, Intervention Rate, Reu...",COCBIR=ECI
9,Central Bank of Colombia,"Colombia, Interest Rate-Median, Reuters Polls,...",pCOCBIR=M

### Search For People

In [15]:
response = search.Definition(
    query="cfo",
    view=search.Views.PEOPLE
).get_data()

response.data.df

,BusinessEntity,DocumentTitle,PermID,PI
0,PERSON,Amy E. Hood - Microsoft Corp - Chief Financial...,34415553383,34415553383
1,PERSON,Luca Maestri - Apple Inc - Chief Financial Off...,34414554748,34414554748
2,PERSON,Brian T. Olsavsky - Amazon.com Inc - Chief Fin...,34417610894,34417610894
3,PERSON,Ruth M. Porat - Alphabet Inc - Chief Financial...,34413960665,34413960665
4,PERSON,David M. Wehner - Meta Platforms Inc - Chief F...,34414804241,34414804241
5,PERSON,Marc D. Hamburg - Berkshire Hathaway Inc - Chi...,34413152672,34413152672
6,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO...,34414966250,34414966250
7,PERSON,Xu Hong - Alibaba Group Holding Ltd - Chief Fi...,34425652371,34425652371
8,PERSON,John Lo - Tencent Holdings Ltd - Chief Financi...,34414907131,34414907131
9,PERSON,Vasant M. Prabhu - Visa Inc - Vice Chairman of...,34413340523,34413340523

## Close the session

In [16]:
rd.close_session()